# Lazygit Configuration
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

gui:
  # Theme
  theme:
    activeBorderColor:
      - "#ff87d7"
      - bold
    inactiveBorderColor:
      - "#5fff87"
    searchingActiveBorderColor:
      - "#ffaf5f"
      - bold
    optionsTextColor:
      - "#5fff87"
    selectedLineBgColor:
      - "#3b4252"
    cherryPickedCommitFgColor:
      - "#ff87d7"
    cherryPickedCommitBgColor:
      - "#5e81ac"
    markedBaseCommitFgColor:
      - "#5fff87"
    markedBaseCommitBgColor:
      - "#3b4252"
    unstagedChangesColor:
      - "#ff6b6b"
    defaultFgColor:
      - default

  # Layout
  showFileTree: true
  showListFooter: true
  showRandomTip: false
  showCommandLog: true
  showBottomLine: true
  showPanelJumps: true

  # Sizing
  sidePanelWidth: 0.3333
  expandFocusedSidePanel: false
  mainPanelSplitMode: "flexible"

  # Border
  border: "rounded"

  # Time format
  timeFormat: "02 Jan 06"
  shortTimeFormat: "3:04PM"

  # Commit length
  commitLength:
    show: true

  # Mouse support
  mouseEvents: true

  # Skip discard warning
  skipDiscardChangeWarning: false
  skipStashWarning: false
  skipNoStagedFilesWarning: false
  skipRewordInEditorWarning: false

  # Command log size
  commandLogSize: 8

  # Spinner
  spinner:
    frames:
      - "⣾"
      - "⣽"
      - "⣻"
      - "⢿"
      - "⡿"
      - "⣟"
      - "⣯"
      - "⣷"
    rate: 50

git:
  # Paging
  paging:
    colorArg: always
    pager: delta --dark --paging=never

  # Commit
  commit:
    signOff: false
    autoWrapCommitMessage: true
    autoWrapWidth: 72

  # Merging
  merging:
    manualCommit: false
    args: ""

  # Pull
  pulling:
    mode: "auto"

  # Skip hook prefix
  skipHookPrefix: WIP

  # Auto fetch
  autoFetch: true
  autoRefresh: true
  fetchAll: true

  # Branches
  branchLogCmd: 'git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit'

  # Overrides
  overrideGpg: false

  # Disable force pushing
  disableForcePushing: false

  # Parse emoji
  parseEmoji: true

os:
  # Edit command
  edit: "hx {{filename}}"
  editAtLine: "hx {{filename}}:{{line}}"
  editAtLineAndWait: "hx {{filename}}:{{line}}"

  # Edit in terminal
  editInTerminal: true

  # Open command
  open: "open {{filename}}"

  # Open link command
  openLink: "open {{link}}"

refresher:
  # Refresh interval in seconds
  refreshInterval: 10

  # Fetch interval in seconds
  fetchInterval: 60

update:
  # Check for updates
  method: prompt
  days: 14

confirmOnQuit: false

# Custom commands
customCommands:
  - key: "<c-r>"
    command: "git rebase -i {{.SelectedLocalCommit.Sha}}"
    context: "commits"
    description: "Interactive rebase from selected commit"

  - key: "C"
    command: "git commit --amend --no-edit"
    context: "files"
    description: "Amend commit without editing message"

  - key: "E"
    command: "hx {{.SelectedFile.Name}}"
    context: "files"
    description: "Edit file in Helix"

  - key: "O"
    command: "open {{.SelectedFile.Name}}"
    context: "files"
    description: "Open file in default application"

keybinding:
  universal:
    quit: "q"
    quit-alt1: "<c-c>"
    return: "<esc>"
    quitWithoutChangingDirectory: "Q"
    togglePanel: "<tab>"
    prevItem: "<up>"
    nextItem: "<down>"
    prevItem-alt: "k"
    nextItem-alt: "j"
    prevPage: ","
    nextPage: "."
    scrollLeft: "H"
    scrollRight: "L"
    gotoTop: "<"
    gotoBottom: ">"
    toggleRangeSelect: "v"
    rangeSelectDown: "<s-down>"
    rangeSelectUp: "<s-up>"
    prevBlock: "<left>"
    nextBlock: "<right>"
    prevBlock-alt: "h"
    nextBlock-alt: "l"
    nextBlock-alt2: "<tab>"
    prevBlock-alt2: "<backtab>"
    jumpToBlock: ["1", "2", "3", "4", "5"]
    nextMatch: "n"
    prevMatch: "N"
    startSearch: "/"
    optionMenu: null
    optionMenu-alt1: "?"
    select: "<space>"
    goInto: "<enter>"
    confirm: "<enter>"
    confirmInEditor: "<a-enter>"
    remove: "d"
    new: "n"
    edit: "e"
    openFile: "o"
    scrollUpMain: "<pgup>"
    scrollDownMain: "<pgdown>"
    scrollUpMain-alt1: "K"
    scrollDownMain-alt1: "J"
    scrollUpMain-alt2: "<c-u>"
    scrollDownMain-alt2: "<c-d>"
    createRebaseOptionsMenu: "m"

    # Diffing
    diffingMenu: "W"
    diffingMenu-alt: "<c-e>"

    pushFiles: "P"
    pullFiles: "p"
    refresh: "R"
    createPatchOptionsMenu: "<c-p>"
    nextTab: "]"
    prevTab: "["
    nextScreenMode: "+"
    prevScreenMode: "_"
    undo: "z"
    redo: "<c-z>"
    filteringMenu: "<c-s>"
    copyToClipboard: "<c-o>"
    openRecentRepos: "<c-r>"
    submitEditorText: "<enter>"
    extrasMenu: "@"
    toggleWhitespaceInDiffView: "<c-w>"
    increaseContextInDiffView: "}"
    decreaseContextInDiffView: "{"
    increaseRenameSimilarityThreshold: ")"
    decreaseRenameSimilarityThreshold: "("
    openDiffTool: "<c-t>"
